ARG NODE_VERSION=20

FROM node:$NODE_VERSION-buster AS base

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --ignore-scripts

COPY . .

RUN yarn lerna bootstrap
RUN rm -rf /app/packages/client/dist/ && yarn build --scope=client

CMD ["yarn", "dev", "--scope=client"]
